name: testshop.qa-practice.com tests

on:
  workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Testshop Selenium tests
        run: pytest

      - name: Install Allure CLI
        run: sudo npm install -g allure-commandline --unsafe-perm=true

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages